import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {
    
    String tempRows;
    static int finalRows; // Number in rowsField, input.
    
    public int getRows(){
        finalRows = Integer.parseInt(tempRows);            
        return finalRows;
    }
    
    public Main() {
        initComponents();
        
        getContentPane().setBackground(new Color(79,179,164));
        
        //pascal.setBorderPainted(false); 
        //pascal.setContentAreaFilled(false); 
        //pascal.setFocusPainted(false); 
        //pascal.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pascal = new javax.swing.JButton();
        quincunx = new javax.swing.JButton();
        rowsField = new javax.swing.JTextField();
        javax.swing.JLabel labelRows = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pascal.setBackground(new java.awt.Color(175, 66, 56));
        pascal.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        pascal.setForeground(new java.awt.Color(251, 254, 233));
        pascal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pascal.png"))); // NOI18N
        pascal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pascalActionPerformed(evt);
            }
        });
        getContentPane().add(pascal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        quincunx.setBackground(new java.awt.Color(175, 66, 56));
        quincunx.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        quincunx.setForeground(new java.awt.Color(251, 254, 233));
        quincunx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quincunx.png"))); // NOI18N
        quincunx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quincunxActionPerformed(evt);
            }
        });
        getContentPane().add(quincunx, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        rowsField.setBackground(new java.awt.Color(124, 132, 137));
        rowsField.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        rowsField.setForeground(new java.awt.Color(251, 254, 233));
        getContentPane().add(rowsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 43, -1));

        labelRows.setBackground(new java.awt.Color(124, 132, 137));
        labelRows.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        labelRows.setForeground(new java.awt.Color(251, 254, 233));
        labelRows.setText("Filas del triángulo:");
        getContentPane().add(labelRows, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/delgados/Downloads/prisma.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pascalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pascalActionPerformed
        
    }//GEN-LAST:event_pascalActionPerformed

    private void quincunxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quincunxActionPerformed
        tempRows = rowsField.getText(); // Gets the number in rowsField.
        
        Controller.validateData(tempRows); // Using MVC model.
    }//GEN-LAST:event_quincunxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pascal;
    private javax.swing.JButton quincunx;
    private javax.swing.JTextField rowsField;
    // End of variables declaration//GEN-END:variables
}
